# Generated by Django 5.0.6 on 2024-06-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SelfBankInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invest_amount", models.IntegerField()),
                ("bank_name", models.CharField(default=None, max_length=100)),
                ("loan_rate", models.IntegerField(default=0)),
                ("future_date", models.DateField()),
            ],
        ),
    ]
