# Generated by Django 5.0.6 on 2024-06-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_alter_selfbankinvestment_loan_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfbankinvestment",
            name="interest",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="selfbankinvestment",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
