# Generated by Django 5.0.6 on 2024-06-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0003_selfbankinvestment_interest_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selfbankinvestment",
            old_name="future_date",
            new_name="ROI_Date",
        ),
        migrations.AddField(
            model_name="selfbankinvestment",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
