# Generated by Django 5.0.6 on 2024-06-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0005_alter_selfbankinvestment_created_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selfbankinvestment",
            name="interest",
        ),
        migrations.RemoveField(
            model_name="selfbankinvestment",
            name="total_amount",
        ),
        migrations.AlterField(
            model_name="selfbankinvestment",
            name="bank_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="selfbankinvestment",
            name="invest_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="selfbankinvestment",
            name="loan_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
