# Generated by Django 5.0.6 on 2024-06-07 07:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0006_remove_selfbankinvestment_interest_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selfbankinvestment",
            name="created_date",
        ),
        migrations.AddField(
            model_name="selfbankinvestment",
            name="interest",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="selfbankinvestment",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="selfbankinvestment",
            name="bank_name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="selfbankinvestment",
            name="invest_amount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="selfbankinvestment",
            name="loan_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
    ]
