# Generated by Django 5.0.6 on 2024-06-07 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0007_remove_selfbankinvestment_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfbankinvestment",
            name="created_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
