# Generated by Django 5.0.6 on 2024-06-09 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0009_sector_company_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="company",
        ),
        migrations.CreateModel(
            name="BusinessHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("founded_date", models.DateField()),
                ("headquarters", models.CharField(max_length=200)),
                ("website", models.URLField()),
                ("type_of_service_or_product", models.CharField(max_length=200)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_houses",
                        to="business.sector",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
