# Generated by Django 5.0.6 on 2024-06-10 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "business",
            "0010_remove_service_company_businesshouse_delete_company_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businesshouse",
            name="sector",
        ),
        migrations.DeleteModel(
            name="Sector",
        ),
    ]
