# Generated by Django 5.0.6 on 2024-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0011_remove_businesshouse_sector_delete_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("daily_income", models.FloatField()),
                ("daily_expenses", models.FloatField()),
                ("initial_investment", models.FloatField()),
                ("total_investment", models.FloatField()),
                ("discount_rate", models.FloatField()),
                ("operational_days", models.IntegerField()),
                ("project_lifetime", models.IntegerField()),
            ],
        ),
    ]
