# Generated by Django 5.0.6 on 2024-06-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0012_financialdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdata",
            name="business_house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_data",
                to="business.businesshouse",
            ),
        ),
        migrations.AddField(
            model_name="selfbankinvestment",
            name="name",
            field=models.CharField(default="Default Name", max_length=100),
        ),
        migrations.AlterField(
            model_name="businesshouse",
            name="name",
            field=models.CharField(default="Default Name", max_length=100),
        ),
        migrations.AlterField(
            model_name="selfbankinvestment",
            name="invest_amount",
            field=models.IntegerField(default=0),
        ),
    ]
