# Generated by Django 5.0.6 on 2024-06-12 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0015_alter_businesshousedata_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="financialdata",
            old_name="daily_expenses",
            new_name="daily_expenses_extra",
        ),
        migrations.CreateModel(
            name="BusinessHouseRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relationship_type", models.CharField(max_length=100)),
                (
                    "from_business_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_businesses",
                        to="business.businesshousedata",
                    ),
                ),
                (
                    "to_business_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_businesses",
                        to="business.businesshousedata",
                    ),
                ),
            ],
        ),
    ]
