# Generated by Django 5.0.6 on 2024-06-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("deposit_type", models.CharField(max_length=20)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("from_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("future_date", models.DateField()),
                ("bank_name", models.CharField(default="Default Bank", max_length=100)),
                (
                    "deposit_type",
                    models.CharField(default="Default Deposit Type", max_length=100),
                ),
                ("amount", models.IntegerField()),
                ("total_interest", models.IntegerField(default=0)),
                ("total_amount", models.IntegerField(default=0)),
                ("days", models.IntegerField(default=0)),
            ],
        ),
    ]
